name: Auto-Merge
description: Automerging knowl docs
inputs:
  KNOWL_USER_EMAIL:
    description: KNOWL_USER_EMAIL
    required: true
  KNOWL_USER_PASS:
    description: KNOWL_USER_PASS
    required: true
  OPENAI_API_KEY:
    description: OPENAI_API_KEY
    required: false
runs:
  using: composite
  steps:
    - name: Branch info
      run: |
          echo "GITHUB_HEAD_REF"
          echo ${GITHUB_HEAD_REF}
          echo "GITHUB_BASE_REF"
          echo ${GITHUB_BASE_REF}
          echo "GITHUB_REFy"
          echo ${GITHUB_REF}
          echo "baseref"
          echo ${{github.base_ref}}
          echo "headref"
          echo ${{github.head_ref}}
      shell: bash
    - name: Run script file
      run: chmod +x "${{ github.action_path }}/run-gen-docs.sh"
      shell: bash
    - name: Run script file
      run: run-gen-docs.sh 
      shell: bash
      env:
        KNOWL_USER_EMAIL: ${{inputs.KNOWL_USER_EMAIL}}
        KNOWL_USER_PASS: ${{inputs.KNOWL_USER_PASS}}
        OPENAI_API_KEY: ${{inputs.OPENAI_API_KEY}}
