name: 'Generate AI docs'
description: 'Generate AI doc'

inputs:
  input_one:
    description: 'input_one'
    
runs:
  using: "composite"
  steps:
      - run: echo "hello"
        shell: shell
      - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
        shell: shell
      - run: echo "${{inputs.input_one}}"
        shell: shell
      - run: ls
        shell: shell
      - run: ls ${{ github.workspace }}
        shell: shell
      - run: ls ${{ github.action_path }}
        shell: shell
      - name: Run script file
        run: chmod +x "${{ github.action_path }}/test.sh"
        shell: shell
      - name: Run script file
        run: test.sh
        shell: shell
