---
name: Generate AI docs
description: Generate AI doc
inputs:
  KNOWL_USER_EMAIL:
    description: KNOWL_USER_EMAIL
    required: true
  KNOWL_USER_PASS:
    description: KNOWL_USER_PASS
    required: true
  OPENAI_API_KEY:
    description: OPENAI_API_KEY
    required: true
runs:
  using: composite
  steps:
    - run: echo "hello"
      shell: bash
    - run: echo "${{ github.action_path }}" >> "$GITHUB_PATH"
      shell: bash
    - run: echo "${{ inputs.KNOWL_USER_EMAIL }}" >> "$KNOWL_USER_EMAIL"
      shell: bash
    - run: echo "${{ inputs.KNOWL_USER_PASS }}" >> "$KNOWL_USER_PASS"
      shell: bash
    - run: echo "${{ inputs.OPENAI_API_KEY }}" >> "$OPENAI_API_KEY"
      shell: bash
    - name: setup python environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install python-dotenv
      shell: bash
