name: 'Generate AI docs'
description: 'Generate AI doc'

inputs:
  input_one:
    description: 'input_one'
    
runs:
  using: "composite"
  steps:
      - run: echo "hello"
        shell: bash
      - run: echo "${{inputs.input_one}}"
        shell: bash
      - name: Run script file
        run: |
           cd ${{ github.workspace }}
           chmod +x ./test.sh
           ./test.sh
        shell: bash
