name: Generate AI docs
description: Generate AI doc
inputs:
  KNOWL_USER_EMAIL:
    description: KNOWL_USER_EMAIL
    required: true
  KNOWL_USER_PASS:
    description: KNOWL_USER_PASS
    required: true
  OPENAI_API_KEY:
    description: OPENAI_API_KEY
    required: true

runs:
  using: composite
  steps:
    - run: echo "hello"
      shell: bash
    - run: |
        echo "${{ github.action_path }}" >> $GITHUB_PATH
        echo "${{ inputs.KNOWL_USER_EMAIL }}" >> $KNOWL_USER_EMAIL
        echo "${{ inputs.KNOWL_USER_PASS }}" >> $KNOWL_USER_PASS
        echo "${{ inputs.OPENAI_API_KEY }}" >> $OPENAI_API_KEY
      shell: bash
    - name: setup python environment
      uses: actions/setup-python@v4
      shell: bash
      with:
        python-version: 3.9
    - run: ls
      shell: bash
    - run: ls ${{ github.workspace }}
      shell: bash
    - run: ls ${{ github.action_path }}
      shell: bash
    - name: Run script file
      run: chmod +x "${{ github.action_path }}/test.sh"
      shell: bash
    - name: Run script file
      run: test.sh
      shell: bash
